package com.unitt.router;

import org.junit.Assert;

/**
 * Base class for Router testing
 *
 * @author: Generated by the Rio Archetype
 */
public abstract class ITAbstractRouterTest {

    void testService(Router service) {
        Assert.assertNotNull(service);
        /* Add your testing code here ...*/
    }
}
