package com.unitt.router;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.rioproject.test.RioTestRunner;
import org.rioproject.test.SetTestManager;
import org.rioproject.test.TestManager;

/**
 * Testing the Router service using the Rio test framework
 *
 * @author: Generated by the Rio Archetype
 */
@RunWith(RioTestRunner.class)
public class ITRouterDeployTest extends ITAbstractRouterTest {
	@SetTestManager
    static TestManager testManager;
    Router service;

    @Before
    public void setup() throws Exception {
	    Assert.assertNotNull(testManager);       
        service = (Router)testManager.waitForService(Router.class); 
    }

    @Test
    public void test1() {
        testService(service);
    }
}
