package com.unitt.commons.authorization;


import org.junit.Assert;


/**
 * Base class for Authorization testing
 * 
 * @author: Generated by the Rio Archetype
 */
public abstract class ITAbstractAuthorizationTest
{
    void testService( Authorization service )
    {
        Assert.assertNotNull( service );
        /* Add your testing code here ... */
    }
}
