package com.unitt.commons.authorization;


import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.rioproject.test.RioTestRunner;
import org.rioproject.test.SetTestManager;
import org.rioproject.test.TestManager;


/**
 * Testing the Authorization service using the Rio test framework
 * 
 * @author: Generated by the Rio Archetype
 */
@RunWith( RioTestRunner.class )
public class ITAuthorizationDeployTest extends ITAbstractAuthorizationTest
{
    @SetTestManager
    static TestManager testManager;
    Authorization      service;

    @Before
    public void setup() throws Exception
    {
        Assert.assertNotNull( testManager );
        service = (Authorization) testManager.waitForService( Authorization.class );
    }

    @Test
    public void test1()
    {
        testService( service );
    }
}
