package com.unitt.commons.authentication;


import org.junit.Assert;


/**
 * Base class for Authentication testing
 * 
 * @author: Generated by the Rio Archetype
 */
public abstract class ITAbstractAuthenticationTest
{

    void testService( Authentication service )
    {
        Assert.assertNotNull( service );
        /* Add your testing code here ... */
    }
}
