package com.unitt.router;


import com.unitt.servicemanager.hazelcast.routing.HazelcastMessageRouter;
import com.unitt.servicemanager.websocket.MessageRoutingInfo;
import org.rioproject.bean.Initialized;
import org.rioproject.bean.PostUnAdvertise;
import org.rioproject.bean.PreAdvertise;
import org.rioproject.core.jsb.ServiceBeanContext;
import org.rioproject.watch.StopWatch;


/**
 * Router service implementation
 *
 * @author Generated by the Rio Archetype
 */
public class RouterImpl extends HazelcastMessageRouter implements Router {
    protected StopWatch time;

    @Initialized
    public void initialize() {
        super.initialize();
    }

    public void setServiceBeanContext(ServiceBeanContext context) {
        time = new StopWatch("time");
        context.getWatchRegistry().register(time);
    }

    @Override
    public void process(MessageRoutingInfo aInfo) {
        time.startTiming();
        super.process(aInfo);
        time.stopTiming();
    }

    @PreAdvertise
    public void onAdvertise() {
        start();
    }

    @PostUnAdvertise
    public void onUnadvertise() {
        stop();
    }
}
